name: default-config
services:
  development:
    image: ${DOCKER_IMAGENAME}
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ${DOCKER_WORKSPACE}:${DOCKER_HOME}
      - ${HOME}/.ssh:${DOCKER_HOME}/.ssh:ro
      - ${HOME}/.gitconfig:${DOCKER_HOME}/.gitconfig:ro
      - ${HOME}/.git-credentials:${DOCKER_HOME}/.git-credentials:ro
      - ${HOME}/.vim:${DOCKER_HOME}/.vim:ro
      - ${HOME}/.vimrc:${DOCKER_HOME}/.vimrc:ro
    devices:
      - /dev/net/tun:/dev/net/tun
